### ISSUE TITLE
can't run plotavx2

### ISSUE THREAD

**Issue by ITwrx** [Mirkic7/mdcct#4]
i tried to use "./plotavx2 -k BURST-key!-key!-key!! -x 1 -d /path/to/hdd -m 8192 -t 8 -a"
and it outputs:
 
Async mode set.
Using SSE2 core.
Usage: ./plotavx2 -k KEY [ -x CORE ] [-d DIRECTORY] [-s STARTNONCE] [-n NONCES] [-m STAGGERSIZE] [-t THREADS] -a
   CORE:
     0 - default core
     1 - SSE2 core
     2 - AVX2 core
   -a = ASYNC writer mode (will use 2x memory!)

like it starts to work then complinas about my usage. i don't understand why it wouldn't complain about the usage first if there were a problem with the command.
i'm using arch linux, if that matters any.
thanks

**Comment by Mirkic7** [comment]
You need to put key in numeric mode (so it's one string of numbers), not in 'BURST-xxxx-xxxx-xxxx' type.

**Comment by ITwrx** [comment]
thanks, man. It's plotting now.
