### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by jxer** [Mirkic7/mdcct#5]
not sure what im doing wrong at all

./plotavx2 -k numericburstid -x 1 -d /home/jxer/ -s 0 -n 7495680 -m 1024 -t 1
Using SSE2 core.
Usage: ./plotavx2 -k KEY [ -x CORE ] [-d DIRECTORY] [-s STARTNONCE] [-n NONCES] [-m STAGGERSIZE] [-t THREADS] -a
   CORE:
     0 - default core
     1 - SSE2 core
     2 - AVX2 core
   -a = ASYNC writer mode (will use 2x memory!)

**Comment by whardier** [comment]
Same here.  Not sure what I'm doing wrong but it seems like one of the arguments is looking for a unit size.

**Comment by Mirkic7** [comment]
Are you using KEY in numeric form?

**Comment by whardier** [comment]
About 10 minutes ago I tried that ;)  Thanks - it's attempting to deal with
a large data set now.



[image: --]

Shane R. Spencer
[image: https://]about.me/ShaneSpencer
<https://about.me/ShaneSpencer?promo=email_sig>

**Comment by jxer** [comment]
can you provide example of what your talking about?

is it the Numeric Account ID: in the burst wallet?

**Comment by whardier** [comment]
Once I tried the numeric ID it started working.  Now I need to figure out
how to set a reward assignment and mine.



[image: --]

Shane R. Spencer
[image: https://]about.me/ShaneSpencer
<https://about.me/ShaneSpencer?promo=email_sig>
